# This is a basic workflow that is manually triggered

name: Manual Publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The branch, tag or SHA to checkout. When checking out the repository that
          triggered a workflow, this defaults to the reference or SHA for that event.
          Otherwise, uses the default branch.
        required: true
        default: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  list_extensions:
    runs-on: ubuntu-latest
    outputs:
      extension_list: ${{ env.EXTENSION_LIST }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: From Script
        run: |
          echo extensions_from_script=$(./scripts/list-extensions.sh) >> $GITHUB_ENV

      - name: EXTENSION_LIST
        env:
          EXTENSION_LIST: ${{ env.extensions_from_script }}
        run: |
          echo EXTENSION_LIST=$EXTENSION_LIST >> $GITHUB_ENV

  publish:
    needs:
      - list_extensions
    uses: ./.github/workflows/publish.yml
    with:
      ref: ${{ inputs.ref }}
      paths_released: ${{ needs.list_extensions.outputs.extension_list }}
    secrets:
      VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
      OVSX_TOKEN: ${{ secrets.OVSX_TOKEN }}
# cspell:ignore vsix xargs OVSX
