name: release-please

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      release_please_info: ${{ toJSON(steps.release.outputs) }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest

  release-info:
    runs-on: ubuntu-latest
    needs:
      - release-please
    env:
      release_please_info: ${{ needs.release-please.outputs.release_please_info }}
    steps:
      - name: Show Release Please Results
        run: echo "$release_please_info"

  # publish:
  #   needs:
  #     - release-please
  #   uses: ./.github/workflows/publish.yml
  #   secrets:
  #     PUBLISH_NPM: ${{ secrets.PUBLISH_NPM }}
  #   if: ${{ needs.release-please.outputs.release_created }}
# cspell:ignore noreply
