name: " 🔗 Update Extension Lists"

on:
  push:
    branches:
      - main

  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 0"

jobs:
  update-extension-lists:
    if: github.repository_owner == 'streetsidesoftware'
    runs-on: ubuntu-latest
    env:
      NEW_BRANCH: "update-extension-lists"
    steps:
      - name: Start
        run: |
          echo "${{ toJson(github.event.inputs) }}"
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Install
        run: npm install

      - name: Update Workspace
        run: |
          ./scripts/update-code-workspace.sh

      - name: Update Release Please Packages
        run: |
          ./scripts/gen-release-please-config.sh

      - name: PR
        uses: ./.github/actions/pr
        with:
          commit-message: "ci: Update Extension Lists"
          branch: ${{ env.NEW_BRANCH }}
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          app_private_key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
